server:
  port: '9090'
spring:
  application:
    name: login
  #  profiles:
  #    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: tbs
    url: jdbc:postgresql://localhost:5432/login
    password: tbs@123abc
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  app:
    jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    jwtExpirationMs: 86400000 # 1 day